package rhizome.node;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

import org.junit.jupiter.api.Test;

import rhizome.core.blockchain.NetworkParameters;

/**
 * Confronts the checked-in {@code scripts/local-testnet/profiles/*.env} artifacts against the
 * live {@link NetworkParameters} profiles they claim to mirror.
 *
 * <p>The local testnet harness ({@code scripts/local-testnet/}) used to hand-copy a handful of
 * consensus constants (difficulty bounds, retarget lookback, the future-time bound, the prune
 * floor, ...) into each battery that needed them ({@code suite-pow.sh}, {@code
 * suite-bootstrap.sh}) — a duplication with nothing to catch it drifting from the real profile.
 * {@code profiles/*.env} is now the single checked-in artifact those batteries source (via
 * {@code common.sh}'s {@code NETWORK}/{@code PROFILE_FILE} plumbing), generated by {@code
 * scripts/local-testnet/tools/ProfileDump.java}. This test is the machine check that closes the
 * loop: a profile that changes without regenerating and reviewing the matching {@code .env} file
 * fails the build here, instead of letting a battery run — and pass — under a stale mirror of the
 * real profile.
 *
 * <p>Deliberately reads the checked-in file from disk and asserts it against {@code
 * NetworkParameters}'s own public accessors, rather than shelling out to {@code ProfileDump} and
 * diffing its output against itself (which would prove nothing about the checked-in artifact).
 */
class TestnetProfileMirrorTest {

    @Test
    void devnetProfileMirrorsNetworkParameters() throws IOException {
        assertProfileMatches("devnet", NetworkParameters.devnet());
    }

    @Test
    void stagingProfileMirrorsNetworkParameters() throws IOException {
        assertProfileMatches("staging", NetworkParameters.staging());
    }

    private static void assertProfileMatches(String network, NetworkParameters params) throws IOException {
        Path profilePath = repoRoot().resolve("scripts/local-testnet/profiles/" + network + ".env");
        assertTrue(Files.exists(profilePath), "missing checked-in profile: " + profilePath);
        Map<String, String> profile = parseEnvFile(profilePath);

        // Same formula as NodeConfig.parseKeepBlocks — the safe RHIZOME_PRUNE floor, derived from
        // the deepest history the engine may read (reorg, uncle, difficulty, median-time windows)
        // plus NodeConfig's own safety margin. Read from NodeConfig directly (package-private
        // PRUNE_MARGIN) rather than a third hand-copy of 128.
        int pruneFloor = Math.max(Math.max(params.maxReorgDepth(), params.uncleMaxDepth()),
            Math.max(params.difficultyLookback(), params.medianTimeWindow())) + NodeConfig.PRUNE_MARGIN;

        Map<String, String> expected = new LinkedHashMap<>();
        expected.put("CHAIN_ID", String.valueOf(params.chainId()));
        expected.put("NETWORK_NAME", params.networkName());
        expected.put("POW_ALGORITHM", params.powAlgorithm().name());
        expected.put("DIFFICULTY_LOOKBACK", String.valueOf(params.difficultyLookback()));
        expected.put("MIN_DIFFICULTY", String.valueOf(params.minDifficulty()));
        expected.put("MAX_DIFFICULTY", String.valueOf(params.maxDifficulty()));
        expected.put("GENESIS_DIFFICULTY", String.valueOf(params.genesisDifficulty()));
        expected.put("DESIRED_BLOCK_TIME_SEC", String.valueOf(params.desiredBlockTimeSec()));
        expected.put("MAX_FUTURE_BLOCK_TIME_SEC", String.valueOf(params.maxFutureBlockTimeSec()));
        expected.put("MEDIAN_TIME_WINDOW", String.valueOf(params.medianTimeWindow()));
        expected.put("MIN_FEE", String.valueOf(params.minFee()));
        expected.put("MAX_REORG_DEPTH", String.valueOf(params.maxReorgDepth()));
        expected.put("MAX_UNCLES_PER_BLOCK", String.valueOf(params.maxUnclesPerBlock()));
        expected.put("UNCLE_MAX_DEPTH", String.valueOf(params.uncleMaxDepth()));
        expected.put("PRUNE_FLOOR", String.valueOf(pruneFloor));

        assertEquals(expected.keySet(), profile.keySet(), network + ".env's key set has drifted from "
            + "what NetworkParameters." + network + "() reports — regenerate it with ProfileDump "
            + "(see the file's header for the exact command)");
        for (Map.Entry<String, String> entry : expected.entrySet()) {
            assertEquals(entry.getValue(), profile.get(entry.getKey()),
                network + ".env: " + entry.getKey() + " has drifted from NetworkParameters." + network
                    + "() — regenerate scripts/local-testnet/profiles/" + network + ".env with "
                    + "ProfileDump (see the file's header for the exact command)");
        }
    }

    /** Parses a shell-sourceable {@code KEY=VALUE} file, skipping comments and blank lines. */
    private static Map<String, String> parseEnvFile(Path path) throws IOException {
        Map<String, String> values = new LinkedHashMap<>();
        for (String line : Files.readAllLines(path)) {
            String trimmed = line.strip();
            if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                continue;
            }
            int eq = trimmed.indexOf('=');
            assertTrue(eq > 0, path + ": malformed line (expected KEY=VALUE): " + line);
            values.put(trimmed.substring(0, eq), trimmed.substring(eq + 1));
        }
        return values;
    }

    /**
     * Resolves the repository root by walking up from the working directory looking for {@code
     * settings.gradle} — the same technique {@code rhizome.adversarial.AdversarialProtocolTest}
     * and {@code rhizome.StagingGenesisTest} use to reach a sibling module's files without
     * depending on a build-generated absolute path.
     */
    private static Path repoRoot() {
        Path directory = Path.of("").toAbsolutePath();
        for (Path candidate = directory; candidate != null; candidate = candidate.getParent()) {
            if (Files.exists(candidate.resolve("settings.gradle"))) {
                return candidate;
            }
        }
        throw new IllegalStateException("no settings.gradle above " + directory);
    }
}
